#!/bin/bash
sudo yum update -y
sudo amazon-linux-extras install docker -y
sudo service docker start
sudo usermod -a -G docker ec2-user

sudo yum install git -y

aws --version
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install


curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.9/2020-08-04/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin
kubectl version --short --client

aws eks --region us-east-1 update-kubeconfig --name flask_app
http://172.17.0.18:32604/
kubectl create secret generic server-side-secrets --from-literal=JWT_SECRET=thisIsMySecretKeyForJWT*@.[123

docker image build -t youngwoochun/custom-docker-images:todo-client-kubernetes-app .
docker push youngwoochun/custom-docker-images:todo-client-kubernetes-app
docker image build -t youngwoochun/custom-docker-images:todo-server-kubernetes-app .
docker push youngwoochun/custom-docker-images:todo-server-kubernetes-app
